authz/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='authz'
urlpatterns = [
    path("login", views.ProtectView.as_view(), name='protect'),
]

django_toddler_planner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('schedule_manager.urls')),
    path('admin/', admin.site.urls),
    path('schedule/', include('schedule_manager.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

schedule_manager/urls.py
from django.urls import path
from . import views

app_name="schedule_manager"
urlpatterns = [
    path('', views.WeeklyScheduleView.as_view(), name='weeklyschedule_list'),
    path('create', views.WeeklyScheduleCreate.as_view(), name='weeklyschedule_create'),
    path('schedule<int:pk>/update', views.WeeklyScheduleUpdate.as_view(), name='weeklyschedule_update'),
    path('schedule/<int:pk>delete', views.WeeklyScheduleDelete.as_view(), name='weeklyschedule_delete'),
    path('generic', views.Daily_schedule_generic.as_view(), name='daily_schedule_generic'),
]

schedule_manager/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import date, time
from functools import partial
from math import floor

DAYS_OF_WEEK = (
            (0, 'Monday'),
            (1, 'Tuesday'),
            (2, 'Wednesday'),
            (3, 'Thursday'),
            (4, 'Friday'),
            (5, 'Saturday'),
            (6, 'Sunday'),
           )

class Util():
    @classmethod
    def addDays(type_arg, num_days):
        return timezone.now() + timezone.timedelta(days=num_days)

class WeeklySchedule(models.Model):
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #hours_worked = models.IntegerField()
    # todo: pass default date for each day
    day1 = models.ForeignKey('schedule_manager.DailySchedule', on_delete = models.SET_NULL, null = True, related_name='day1')
    day2 = models.ForeignKey('schedule_manager.DailySchedule', on_delete = models.SET_NULL, null = True, related_name='day2' )
    day3 = models.ForeignKey('schedule_manager.DailySchedule', on_delete = models.SET_NULL, null = True, related_name='day3')
    day4 = models.ForeignKey('schedule_manager.DailySchedule', on_delete = models.SET_NULL, null = True, related_name='day4')
    day5 = models.ForeignKey('schedule_manager.DailySchedule', on_delete = models.SET_NULL, null = True, related_name='day5')
    day6 = models.ForeignKey('schedule_manager.DailySchedule', on_delete = models.SET_NULL, null = True, related_name='day6')
    day7 = models.ForeignKey('schedule_manager.DailySchedule', on_delete = models.SET_NULL, null = True, related_name='day7')

    #day1_date = models.DateField(default=timezone.now)
    #day2_date = models.DateField(default=partial(Util.addDays, num_days=1))
    #day3_date = models.DateField(default=partial(Util.addDays, num_days=2))
    #day4_date = models.DateField(default=partial(Util.addDays, num_days=3))
    #day5_date = models.DateField(default=partial(Util.addDays, num_days=4))
    #day6_date = models.DateField(default=partial(Util.addDays, num_days=5))
    #day7_date = models.DateField(default=partial(Util.addDays, num_days=6))

    @property
    def hours_worked(self):
        #self.day1.aggregate(Sum('hours_worked'))
        return self.day1.hours_worked + self.day2.hours_worked  + self.day3.hours_worked  + self.day4.hours_worked  + self.day5.hours_worked  + self.day6.hours_worked  + self.day7.hours_worked 
        #[self.day1, self.day2, self.day3, self.day4, self.day5, self.day6, self.day7].aggregate(Sum('hours_worked'))

    def savedata(self):
        self.save()

    def __str__(self):
        return "{} to {}".format(self.day1.date, self.day7.date)

class DailySchedule(models.Model):
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    start_time = models.TimeField(default=time(hour=8, minute=0))
    end_time = models.TimeField(default=time(hour=16, minute=0))
    day = models.IntegerField(choices=DAYS_OF_WEEK)
    save_date = models.DateTimeField(default=timezone.now)

    @property 
    def hours_worked(self):
        end_minutes = self.end_time.hour*60 + self.end_time.minute
        start_minutes = self. start_time.hour*60 + self.start_time.minute
        return floor((end_minutes - start_minutes) / 60)

    def savedata(self):
        self.save_date = timezone.now()
        self.save()

    def __str__(self):
        return "{}".format(self.date)
        #return "{}:{}".format(self.date, DAYS_OF_WEEK[self.day][1])
    

schedule_manager/forms.py
from django.forms import ModelForm, widgets, DateField
from schedule_manager.models import DailySchedule, WeeklySchedule
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Row, Field, MultiField, Div

class WeeklyScheduleForm(ModelForm):
    class Meta:
        model = WeeklySchedule
        #exclude = ["user"]
        fields = "__all__"

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.layout = Layout(
                Fieldset(
                    'Daily Schedule',
                    'day1',
                    'day2'
                ),
                Submit('submit', 'Submit', css_class='button white'),
            )

class DailyScheduleForm(ModelForm):
    #    def __init__(self, *args, **kwargs):
    #    super().__init__(*args, **kwargs)
#        self.helper = FormHelper()
#        self.helper.form_class = 'form-horizontal'
#        self.helper.label_class = 'col-sm-2'
#        self.helper.field_class = 'col-sm-10'
#        self.helper.form_tag = False
#        self.helper.layout = Layout(
#                Div(
#                    Div(Field('day'), css_class='col-md-3',),
#                    Div(Field('date'), css_class='col-md-3')
#                    ),
#                Div(
#                    Div(Field('start_time'), css_class='col-md-6',),
#                    Div(Field('end_time'), css_class='col-md-6',),
#                    css_class='row',
#                    )
#                )
#                MultiField(
#                    'Day schedule',
#                    Div( 'date','start_time','end_time'))
#                )
#                Row(
#                    Field('date', wrapper_class='col-md-3'),
#                    Field('start_time', wrapper_class='col-md-3'),
#                    Field('end_time', wrapper_class='col-md-9')
#                    )
#                )


    class Meta:
        model = DailySchedule
        exclude = ["user", "weekid", "save_date"]
        #exclude = ["weekid"]
        widgets = {
            'date': widgets.DateInput(attrs={'type': 'date'}),
            'start_time': widgets.DateInput(attrs={'type': 'time'}),
            'end_time': widgets.DateInput(attrs={'type': 'time'}),
        }


class DailyScheduleFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_method = 'post'
        self.form_class = 'form-horizontal'
        self.label_class = 'col-sm-2'
        self.field_class = 'col-sm-10'
        self.form_tag = False
        self.layout = Layout(
                Div(
                    Div(Field('day'), css_class='col-md-3',),
                    Div(Field('date'), css_class='col-md-3')
                    ),
                Div(
                    Div(Field('start_time'), css_class='col-md-6',),
                    Div(Field('end_time'), css_class='col-md-6',),
                    css_class='row',
                    )
                )
        self.render_required_fields = True

schedule_manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import DailySchedule, WeeklySchedule
from .forms import DailyScheduleForm, WeeklyScheduleForm, DailyScheduleFormSetHelper
import datetime
import pprint
from django.views import generic
from django.views.generic.edit import View, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.forms import formset_factory

class WeeklyScheduleView(generic.ListView):
    model = WeeklySchedule

class WeeklyScheduleCreate(View):
    template = 'schedule_manager/weeklyschedule_form.html'
    success_url = reverse_lazy('schedule_manager:weeklyschedule_list')

    def get(self, request):
        DayFormSet = formset_factory(DailyScheduleForm, extra=7, max_num=7, absolute_max=7)
        dayforms = DayFormSet()
        helper = DailyScheduleFormSetHelper()
        #print(dayforms.as_table())
        ctx = {'dayforms': dayforms, 'helper': helper}
        return render(request, self.template, ctx)

    def post(self, request):
        print(str(request.POST))
        DayFormSet = formset_factory(DailyScheduleForm)
        dayforms = DayFormSet(request.POST)
        
        daydata = []
        print("saving..")
        for form in dayforms:
            daydata.append(form.save())

        #TODO: Non-atomic save - change to only save all objects only after all validations are done
        data = {"day1": daydata[0], "day2":daydata[1], "day3":daydata[2], "day4":daydata[3], "day5":daydata[4], "day6":daydata[5], "day7":daydata[6]}
        weeklyform = WeeklyScheduleForm(data)
        if not dayforms.is_valid() or not weeklyform.is_valid():
            print("error while validating forms")
            print("errors = " + str(weeklyform.errors))
            print("non field errors = " + str(weeklyform.non_field_errors))
            ctx = {'dayforms': dayforms, 'weeklyform':weeklyform}
            return render(request, self.template, ctx)

        weeklyform.save()
        return redirect(self.success_url)

class WeeklyScheduleUpdate(View):
    model=WeeklySchedule
    #exclude=["user"]
    success_url=reverse_lazy('schedule_manager:weeklyschedule_list')

class WeeklyScheduleDelete(DeleteView):
    #TODO: delete day entries when week is deleted
    model=WeeklySchedule
    success_url=reverse_lazy('schedule_manager:weeklyschedule_list')


class Daily_schedule_generic(generic.ListView):
    model = DailySchedule

# Create your views here.
def daily_schedule_list(request):
    # Fetch all schedule objects from the model, reverse chronologically ordered
    schedules = DailySchedule.objects.order_by('-date')
    # Construct a dictionary grouped by month-year
    monthly_grouping = {}
    for schedule in schedules:
        month_year = schedule.date.strftime('%b')  + " " + str(schedule.date.year) 
        if month_year not in monthly_grouping:
            monthly_grouping[month_year] = [schedule]
        else:
            monthly_grouping[month_year].append(schedule)

    context = {"monthly_grouping": monthly_grouping}
    return render(request, 'schedule_manager/daily_schedule.html', context)

schedule_manager/templates/schedule_manager/DailySchedule_list.html
{% extends 'schedule_manager/base.html' %}
{% block content %}        
        {% for schedule in dailyschedule_list %}
            <p> <strong><a href="">{{ schedule.date }} </a></strong>
            {{schedule.start_time}} - {{schedule.end_time}} </p>
        {% endfor %}
{% endblock %}

schedule_manager/templates/schedule_manager/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/schedule_manager.css' %}">
        <title>Nanny care schedule</title>
    </head>
    <body>
        <header>
            <h1><a href="/schedule">Nanny Care Schedule</a></h1>
        </header>
        <br/>
       {% block content %}
       {% endblock %} 
    </body>
</html>

schedule_manager/templates/schedule_manager/daily_schedule.html
{% extends 'schedule_manager/base.html' %}
{% block content %}        
    {% for month_year, schedules in monthly_grouping.items%}
        <h2> {{ month_year }} </h2> 
        {% for schedule in schedules %}
            <p> <strong><a href="">{{ schedule.date }} </a></strong>
            {{schedule.start_time}} - {{schedule.end_time}} </p>
        {% endfor %}
    {% endfor %}
{% endblock %}

schedule_manager/templates/schedule_manager/weekly_schedule_form.html
{% extends 'schedule_manager/base.html' %}
{% block content %}        
<form method = "post">
    <p> <label for="start_time">Date</label>
    {% csrf_token %}
</form>
{% endblock %}

schedule_manager/templates/schedule_manager/weeklyschedule_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Schedule </h1>

<p>Are you sure you want to delete the schedule: {{ weeklyschedule }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

schedule_manager/templates/schedule_manager/weeklyschedule_form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
        {% crispy dayforms helper %}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'schedule_manager:weeklyschedule_list' %}' ; return false;" value="Cancel">
  </form>
    <div/>
    <button id="calculateButton" onclick="get_weekly_hours()">Calculate weekly hours!</button>
    <div class="show-weekly-total">
    <span class="rightfloat">
            <span id="weekly-total"></span>
    </span>
</div>
    <script>
        function get_weekly_hours() {
                    weekly_total = 0
                    for (let i = 0; i < 7; i++) {
                                weekly_total += (new Date(document.getElementById("id_form-"+i+"-date").value + " " + document.getElementById("id_form-"+i+"-end_time").value) - new Date(document.getElementById("id_form-"+i+"-date").value + " " + document.getElementById("id_form-"+i+"-start_time").value))/60/60/1000
                            }
                    document.getElementById('weekly-total').innerHTML = weekly_total
                }

    </script>
{% endblock %}

schedule_manager/templates/schedule_manager/weeklyschedule_list.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <a href="{% url 'schedule_manager:weeklyschedule_create' %}">Add a schedule</a>
  {% if weeklyschedule_list %}
  <ul>
    {% for weeklyschedule in weeklyschedule_list %}
      <li>
          {{ weeklyschedule.day1}} - {{weeklyschedule.day7}} 
          (<a href="{% url 'schedule_manager:weeklyschedule_update' weeklyschedule.id %}">Update</a> |
          <a href="{% url 'schedule_manager:weeklyschedule_delete' weeklyschedule.id %}">Delete</a>) <br/>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no schedules in the library.</p>
  {% endif %}
{% endblock %}